name = "ghost-uptime"
main = "src/index.js"
compatibility_date = "2026-09-08"

[triggers]
crons = ["* * * * *"] # 每分钟执行

[[d1_databases]]
binding = "DB"
database_name = "ghost-uptime-db"
# 用户自行运行 npx wrangler d1 create 后填入自己的 ID
database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"