name = "ghost-uptime"
main = "src/index.js"
compatibility_date = "2026-09-08"

[triggers]
crons = ["* * * * *"] # 每分钟执行

[[d1_databases]]
binding = "DB"
database_name = "ghost-uptime-db"
# 用户自行运行 npx wrangler d1 create 后填入自己的 ID
database_id = "17b516a1-0b9b-4f25-96cc-03d9974dc9e4"